package com.smokeythebandicoot.witcherycompanion;

import com.smokeybandicoot.witcherycompanion.Tags;
import com.smokeythebandicoot.witcherycompanion.proxy.CommonProxy;
import com.smokeythebandicoot.witcherycompanion.utils.Mods;
import net.minecraftforge.fml.common.Loader;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLLoadCompleteEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import org.apache.logging.log4j.Logger;
import zone.rong.mixinbooter.ILateMixinLoader;

import java.util.ArrayList;
import java.util.List;


@Mod(
        modid = WitcheryCompanion.MODID,
        version = WitcheryCompanion.MODVERSION,
        name = WitcheryCompanion.MODNAME,
        dependencies = WitcheryCompanion.MODDEPS,
        useMetadata = true)
public class WitcheryCompanion implements ILateMixinLoader {

    public static final String MODID = Tags.MOD_ID;
    public static final String MODNAME = Tags.MOD_NAME;
    public static final String MODVERSION = Tags.VERSION;
    public static final String MODAUTHOR = "SmokeyTheBandicoot";
    public static final String MODCREDITS = "Ashley for Witchery: Resurrected and various contributions";
    public static final String MODURL = "";
    public static final String MODLOGO = "assets/witcherycompanion/logo.png";
    public static final String MODDEPS = "required-before:witchery;before:patchouli";
    public static final String MODDESCRIPTION = "A Companion mod for Witchery: Resurrected, patching bugs, adding " +
            "integrations and introducing modpack maker-oriented features";

    public static Logger logger;

    @Instance(value = MODID)
    public static WitcheryCompanion instance;

    @SidedProxy(clientSide = "com.smokeythebandicoot.witcherycompanion.proxy.ClientProxy",
                serverSide = "com.smokeythebandicoot.witcherycompanion.proxy.CommonProxy")
    public static CommonProxy proxy;


    @EventHandler
    public void onPreInit(FMLPreInitializationEvent event) {
        // Init logger
        logger = event.getModLog();

        // Set mod info
        event.getModMetadata().autogenerated = false;
        event.getModMetadata().name = WitcheryCompanion.MODID;
        event.getModMetadata().credits = WitcheryCompanion.MODCREDITS;
        event.getModMetadata().authorList.clear();
        event.getModMetadata().authorList.add(WitcheryCompanion.MODAUTHOR);
        event.getModMetadata().description = WitcheryCompanion.MODDESCRIPTION;
        event.getModMetadata().url = WitcheryCompanion.MODURL;
        event.getModMetadata().logoFile = WitcheryCompanion.MODLOGO;

        // preInit
        proxy.preInit(event);

    }

    @EventHandler
    public void onInit(FMLInitializationEvent event) {
        proxy.init(event);
    }

    public void onLoad(FMLLoadCompleteEvent event) {
        proxy.load(event);
    }

    @EventHandler
    public void onServerStarting(FMLServerStartingEvent event) {
        proxy.serverStarting(event);
    }


    @Override
    public List<String> getMixinConfigs() {
        List<String> configs = new ArrayList<>();

        // Add Main Patches
        configs.add("mixins.witcherycompanion.json");

        // Add ConArm Patches
        if (Loader.isModLoaded(Mods.CONSTRUCT_ARMORY))
            configs.add("mixins.witcherycompanion.conarm.json");

        return configs;
    }

    public static String prefix(String text) {
        return WitcheryCompanion.MODID + ":" + (text == null ? "<null>" : text);
    }

}