package com.smokeythebandicoot.witcherypatcher;

import com.smokeythebandicoot.witcherypatcher.config.ModConfig;
import com.smokeythebandicoot.witcherypatcher.patches.infusion.symbol.SymbolEffectPatch;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.msrandom.witchery.registry.RegistryWrapper;
import org.apache.logging.log4j.Logger;

@Mod(
        modid = WitcheryPatcher.MODID,
        version = WitcheryPatcher.MODVERSION,
        name = WitcheryPatcher.MODNAME,
        useMetadata = true
)
public class WitcheryPatcher {

    public static final String MODID = "witcherypatcher";
    public static final String MODNAME = "Witchery Patcher";
    public static final String MODVERSION = "1.0";
    public static final String MODDESCRIPTION = "A mod to fix bugs and performance issues in Witchery:Resurrected";
    public static final String MODAUTHOR = "SmokeyTheBandicoot";
    public static final String MODCREDITS = "";
    public static final String MODURL = "";
    public static final String MODLOGO = "assets/witcherypatcher/logo.png";

    public static Logger logger;
    @Instance(value = MODID)
    public static WitcheryPatcher instance;

    @EventHandler
    public void onPreInit(FMLPreInitializationEvent event) {
        logger = event.getModLog();

        // Set mod info
        event.getModMetadata().autogenerated = false;
        event.getModMetadata().name = MODID;
        event.getModMetadata().credits = MODCREDITS;
        event.getModMetadata().authorList.clear();
        event.getModMetadata().authorList.add(MODAUTHOR);
        event.getModMetadata().description = MODDESCRIPTION;
        event.getModMetadata().url = MODURL;
        event.getModMetadata().logoFile = MODLOGO;

        if (ModConfig.MixinConfig.MixinBugfixes.InfusionFixes.fixSoulBrewsPersistency)
            MinecraftForge.EVENT_BUS.register(SymbolEffectPatch.getInstance());

    }
}